{:config {:order 0, :description "Yes! Actually _did_ something and recorded it!", :name :full-round}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :resources] :map]
  [:transform-enable [:main :resources] :swap [{:io.pedestal.app.messages/topic [:game :players :bryn :resources], :value {:food 100, :wood 100, :clay 100, :reed 100, :stone 100, :grain 100, :vegetable 100}}]]
  [:node-create [:main :tick] :map]
  [:transform-enable [:main :tick] :do-tick [{:io.pedestal.app.messages/type :inc, :io.pedestal.app.messages/topic [:tick]}]]
  [:node-create [:main :move] :map]
  [:transform-enable [:main :move] :perform-move [{:io.pedestal.app.messages/topic [:move], :io.pedestal.app.messages.param/player {:read-as :data}, :io.pedestal.app.messages.param/slot {:read-as :data}, :io.pedestal.app.messages.param/targets {:read-as :data}}]]
  [:node-create [:main :game] :map]
  [:node-create [:main :game :game-id] :map]
  [:value [:main :game :game-id] nil 1]
  [:node-create [:main :game :players] :map]
  [:node-create [:main :game :players :mark] :map]
  [:node-create [:main :game :players :mark :board] :map]
  [:node-create [:main :game :players :mark :board 0] :map]
  [:value [:main :game :players :mark :board 0] nil {:hut :wood, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 1] :map]
  [:value [:main :game :players :mark :board 1] nil {:hut :wood, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 2] :map]
  [:value [:main :game :players :mark :board 2] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 3] :map]
  [:value [:main :game :players :mark :board 3] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 4] :map]
  [:value [:main :game :players :mark :board 4] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 5] :map]
  [:value [:main :game :players :mark :board 5] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 6] :map]
  [:value [:main :game :players :mark :board 6] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 7] :map]
  [:value [:main :game :players :mark :board 7] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 8] :map]
  [:value [:main :game :players :mark :board 8] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 9] :map]
  [:value [:main :game :players :mark :board 9] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 10] :map]
  [:value [:main :game :players :mark :board 10] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 11] :map]
  [:value [:main :game :players :mark :board 11] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 12] :map]
  [:value [:main :game :players :mark :board 12] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 13] :map]
  [:value [:main :game :players :mark :board 13] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :board 14] :map]
  [:value [:main :game :players :mark :board 14] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :mark :name] :map]
  [:value [:main :game :players :mark :name] nil "Mark"]
  [:node-create [:main :game :players :mark :family] :map]
  [:value [:main :game :players :mark :family] nil 2]
  [:node-create [:main :game :players :mark :resources] :map]
  [:value [:main :game :players :mark :resources] nil {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:node-create [:main :game :players :mark :moves] :map]
  [:value [:main :game :players :mark :moves] nil []]
  [:node-create [:main :game :players :mark :starting-player] :map]
  [:node-create [:main :game :players :mark :animals] :map]
  [:value [:main :game :players :mark :animals] nil {:sheep 0, :cattle 0, :boar 0}]
  [:node-create [:main :game :players :bryn] :map]
  [:node-create [:main :game :players :bryn :starting-player] :map]
  [:value [:main :game :players :bryn :starting-player] nil true]
  [:node-create [:main :game :players :bryn :board] :map]
  [:node-create [:main :game :players :bryn :board 0] :map]
  [:value [:main :game :players :bryn :board 0] nil {:hut :wood, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 1] :map]
  [:value [:main :game :players :bryn :board 1] nil {:hut :wood, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 2] :map]
  [:value [:main :game :players :bryn :board 2] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 3] :map]
  [:value [:main :game :players :bryn :board 3] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 4] :map]
  [:value [:main :game :players :bryn :board 4] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 5] :map]
  [:value [:main :game :players :bryn :board 5] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 6] :map]
  [:value [:main :game :players :bryn :board 6] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 7] :map]
  [:value [:main :game :players :bryn :board 7] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 8] :map]
  [:value [:main :game :players :bryn :board 8] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 9] :map]
  [:value [:main :game :players :bryn :board 9] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 10] :map]
  [:value [:main :game :players :bryn :board 10] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 11] :map]
  [:value [:main :game :players :bryn :board 11] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 12] :map]
  [:value [:main :game :players :bryn :board 12] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 13] :map]
  [:value [:main :game :players :bryn :board 13] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 14] :map]
  [:value [:main :game :players :bryn :board 14] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :moves] :map]
  [:value [:main :game :players :bryn :moves] nil []]
  [:node-create [:main :game :players :bryn :resources] :map]
  [:value [:main :game :players :bryn :resources] nil {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:node-create [:main :game :players :bryn :name] :map]
  [:value [:main :game :players :bryn :name] nil "Bryn"]
  [:node-create [:main :game :players :bryn :animals] :map]
  [:value [:main :game :players :bryn :animals] nil {:sheep 0, :cattle 0, :boar 0}]
  [:node-create [:main :game :players :bryn :family] :map]
  [:value [:main :game :players :bryn :family] nil 2]
  [:node-create [:main :game :round] :map]
  [:value [:main :game :round] nil 1]
  [:node-create [:main :game :slots] :map]
  [:node-create [:main :game :slots :fishing] :map]
  [:value [:main :game :slots :fishing] nil {:action :fishing, :performed false, :supply 1}]
  [:node-create [:main :game :slots :one-reed] :map]
  [:value [:main :game :slots :one-reed] nil {:action :one-reed, :performed false, :supply 1}]
  [:node-create [:main :game :slots :build-stable] :map]
  [:value [:main :game :slots :build-stable] nil {:action :build-stable, :performed false}]
  [:node-create [:main :game :slots :starting-player] :map]
  [:value [:main :game :slots :starting-player] nil {:action :starting-player, :performed false}]
  [:node-create [:main :game :slots :three-wood] :map]
  [:value [:main :game :slots :three-wood] nil {:action :three-wood, :performed false, :supply 3}]
  [:node-create [:main :game :slots :day-labourer] :map]
  [:value [:main :game :slots :day-labourer] nil {:action :day-labourer, :performed false}]
  [:node-create [:main :game :slots :one-grain] :map]
  [:value [:main :game :slots :one-grain] nil {:action :one-grain, :performed false}]
  [:node-create [:main :game :slots :one-sheep] :map]
  [:value [:main :game :slots :one-sheep] nil {:action :one-sheep, :performed false, :supply 1}]
  [:node-create [:main :game :slots :build-rooms-or-stables] :map]
  [:value [:main :game :slots :build-rooms-or-stables] nil {:action :build-rooms-or-stables, :actions [:build-rooms :build-stables], :performed false}]
  [:node-create [:main :game :slots :fences] :map]
  [:value [:main :game :slots :fences] nil {:action :fences, :performed false}]
  [:node-create [:main :game :slots :plow] :map]
  [:value [:main :game :slots :plow] nil {:action :plow, :performed false}]
  [:node-create [:main :game :slots :build-stables] :map]
  [:value [:main :game :slots :build-stables] nil {:action :build-stables, :performed false}]
  [:node-create [:main :game :slots :build-rooms] :map]
  [:value [:main :game :slots :build-rooms] nil {:action :build-rooms, :performed false}]
  [:node-create [:main :game :slots :sow] :map]
  [:value [:main :game :slots :sow] nil {:action :sow, :performed false}]
  [:node-create [:main :game :slots :major-or-minor-improvement] :map]
  [:value [:main :game :slots :major-or-minor-improvement] nil {:action :major-or-minor-improvement, :performed false}]
  [:node-create [:main :game :slots :one-clay] :map]
  [:value [:main :game :slots :one-clay] nil {:action :one-clay, :performed false, :supply 1}]
  [:node-create [:main :game :next-move] :map]
  [:value [:main :game :next-move] nil {:type :game, :player :bryn}]
  [:node-create [:main :game :moves] :map]
  [:value [:main :game :moves] nil []]
  :break
  [:value [:main :move] nil {:player :bryn, :slot :three-wood, :targets [], :nub 0.5869763919617981}]
  :break
  [:value [:main :game :players :bryn :moves] [] [{:slot :three-wood, :player :bryn, :targets []}]]
  [:value [:main :game :next-move] {:type :game, :player :bryn} {:type :game, :player :mark}]
  [:value [:main :game :players :bryn :resources] {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 0, :wood 3, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :moves] [] [{:slot :three-wood, :player :bryn, :targets [], :round 1}]]
  [:value [:main :game :slots :three-wood] {:action :three-wood, :performed false, :supply 3} {:action :three-wood, :performed :bryn, :supply 0}]
  :break
  [:value [:main :move] {:player :bryn, :slot :three-wood, :targets [], :nub 0.5869763919617981} {:player :mark, :slot :plow, :targets [{:space 2}], :nub 0.6470304720569402}]
  :break
  [:value [:main :game :players :mark :board 2] {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}} {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field true, :resource {:type nil, :number nil}}]
  [:value [:main :game :next-move] {:type :game, :player :mark} {:type :game, :player :bryn}]
  [:value [:main :game :players :mark :moves] [] [{:slot :plow, :player :mark, :targets [{:space 2}]}]]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1}]]
  [:value [:main :game :slots :plow] {:action :plow, :performed false} {:action :plow, :performed :mark}]
  :break
  [:value [:main :move] {:player :mark, :slot :plow, :targets [{:space 2}], :nub 0.6470304720569402} {:player :bryn, :slot :day-labourer, :targets [{:resource :clay}], :nub 0.49208052293397486}]
  :break
  [:value [:main :game :players :bryn :moves] [{:slot :three-wood, :player :bryn, :targets []}] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]}]]
  [:value [:main :game :next-move] {:type :game, :player :bryn} {:type :game, :player :mark}]
  [:value [:main :game :players :bryn :resources] {:food 0, :wood 3, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 1, :wood 3, :clay 1, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1}]]
  [:value [:main :game :slots :day-labourer] {:action :day-labourer, :performed false} {:action :day-labourer, :performed :bryn}]
  :break
  [:value [:main :move] {:player :bryn, :slot :day-labourer, :targets [{:resource :clay}], :nub 0.49208052293397486} {:player :mark, :slot :one-grain, :targets [], :nub 0.1632327032275498}]
  :break
  [:value [:main :game :players :mark :resources] {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 1, :vegetable 0}]
  [:value [:main :game :next-move] {:type :game, :player :mark} {:type :tick}]
  [:value [:main :game :players :mark :moves] [{:slot :plow, :player :mark, :targets [{:space 2}]}] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []}]]
  [:value [:main :game :slots :one-grain] {:action :one-grain, :performed false} {:action :one-grain, :performed :mark}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1}]]
  :break
  [:value [:main :tick] nil 2]
  :break
  [:value [:main :game :round] 1 2]
  [:value [:main :game :slots :one-reed] {:action :one-reed, :performed false, :supply 1} {:action :one-reed, :performed false, :supply 2}]
  [:value [:main :game :slots :fishing] {:action :fishing, :performed false, :supply 1} {:action :fishing, :performed false, :supply 2}]
  [:value [:main :game :slots :one-grain] {:action :one-grain, :performed :mark} {:action :one-grain, :performed false}]
  [:value [:main :game :slots :one-sheep] {:action :one-sheep, :performed false, :supply 1} {:action :one-sheep, :performed false, :supply 2}]
  [:value [:main :game :slots :day-labourer] {:action :day-labourer, :performed :bryn} {:action :day-labourer, :performed false}]
  [:value [:main :game :slots :three-wood] {:action :three-wood, :performed :bryn, :supply 0} {:action :three-wood, :performed false, :supply 3}]
  [:value [:main :game :slots :one-clay] {:action :one-clay, :performed false, :supply 1} {:action :one-clay, :performed false, :supply 2}]
  [:value [:main :game :slots :plow] {:action :plow, :performed :mark} {:action :plow, :performed false}]
  :break
  [:value [:main :move] {:player :mark, :slot :one-grain, :targets [], :nub 0.1632327032275498} {:player :bryn, :slot :two-reed, :targets [], :nub 0.7400869291741401}]
  :break
  [:node-create [:main :error] :map]
  [:value [:main :error] nil "INVALID MOVE!"]
  :break
  [:value [:main :move] {:player :bryn, :slot :two-reed, :targets [], :nub 0.7400869291741401} {:player :bryn, :slot :one-reed, :targets [], :nub 0.7114744014106691}]
  :break
  [:value [:main :game :next-move] {:type :tick} {:type :game, :player :mark}]
  [:value [:main :game :slots :one-reed] {:action :one-reed, :performed false, :supply 2} {:action :one-reed, :performed :bryn, :supply 0}]
  [:value [:main :game :players :bryn :moves] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]}] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []}]]
  [:value [:main :game :players :bryn :resources] {:food 1, :wood 3, :clay 1, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 1, :wood 3, :clay 1, :reed 2, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2}]]
  :break
  [:value [:main :move] {:player :bryn, :slot :one-reed, :targets [], :nub 0.7114744014106691} {:player :mark, :slot :sow, :targets [{:resource :grain, :space 2}], :nub 0.07760276878252625}]
  :break
  [:value [:main :game :players :mark :board 2] {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field true, :resource {:type nil, :number nil}} {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field true, :resource {:type :grain, :number 3}}]
  [:value [:main :game :players :mark :resources] {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 1, :vegetable 0} {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :next-move] {:type :game, :player :mark} {:type :game, :player :bryn}]
  [:value [:main :game :players :mark :moves] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []}] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]}]]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2}]]
  [:value [:main :game :slots :sow] {:action :sow, :performed false} {:action :sow, :performed :mark}]
  :break
  [:value [:main :move] {:player :mark, :slot :sow, :targets [{:resource :grain, :space 2}], :nub 0.07760276878252625} {:player :bryn, :slot :three-wood, :targets [], :nub 0.8085866391193122}]
  :break
  [:value [:main :game :players :bryn :moves] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []}] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []}]]
  [:value [:main :game :next-move] {:type :game, :player :bryn} {:type :game, :player :mark}]
  [:value [:main :game :players :bryn :resources] {:food 1, :wood 3, :clay 1, :reed 2, :stone 0, :grain 0, :vegetable 0} {:food 1, :wood 6, :clay 1, :reed 2, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2}]]
  [:value [:main :game :slots :three-wood] {:action :three-wood, :performed false, :supply 3} {:action :three-wood, :performed :bryn, :supply 0}]
  :break
  [:value [:main :move] {:player :bryn, :slot :three-wood, :targets [], :nub 0.8085866391193122} {:player :mark, :slot :fishing, :targets [], :nub 0.7990954539272934}]
  :break
  [:value [:main :game :players :mark :resources] {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 2, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :slots :fishing] {:action :fishing, :performed false, :supply 2} {:action :fishing, :performed :mark, :supply 0}]
  [:value [:main :game :next-move] {:type :game, :player :mark} {:type :tick}]
  [:value [:main :game :players :mark :moves] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]}] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []}]]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2}]]
  :break
  [:value [:main :tick] 2 3]
  :break
  [:value [:main :game :round] 2 3]
  [:value [:main :game :slots :one-reed] {:action :one-reed, :performed :bryn, :supply 0} {:action :one-reed, :performed false, :supply 1}]
  [:value [:main :game :slots :fishing] {:action :fishing, :performed :mark, :supply 0} {:action :fishing, :performed false, :supply 1}]
  [:value [:main :game :slots :one-sheep] {:action :one-sheep, :performed false, :supply 2} {:action :one-sheep, :performed false, :supply 3}]
  [:value [:main :game :slots :three-wood] {:action :three-wood, :performed :bryn, :supply 0} {:action :three-wood, :performed false, :supply 3}]
  [:value [:main :game :slots :one-clay] {:action :one-clay, :performed false, :supply 2} {:action :one-clay, :performed false, :supply 3}]
  [:value [:main :game :slots :sow] {:action :sow, :performed :mark} {:action :sow, :performed false}]
  :break
  [:value [:main :move] {:player :mark, :slot :fishing, :targets [], :nub 0.7990954539272934} {:player :bryn, :slot :build-rooms, :targets [{:space 2}], :nub 0.2956515494734049}]
  :break
  [:value [:main :game :next-move] {:type :tick} {:type :game, :player :mark}]
  [:value [:main :game :players :bryn :moves] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []}] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []} {:slot :build-rooms, :player :bryn, :targets [{:space 2}]}]]
  [:value [:main :game :players :bryn :resources] {:food 1, :wood 6, :clay 1, :reed 2, :stone 0, :grain 0, :vegetable 0} {:food 1, :wood 1, :clay 1, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3}]]
  [:value [:main :game :players :bryn :board 2] {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}} {:hut :wood, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:value [:main :game :slots :build-rooms] {:action :build-rooms, :performed false} {:action :build-rooms, :performed :bryn}]
  :break
  [:value [:main :move] {:player :bryn, :slot :build-rooms, :targets [{:space 2}], :nub 0.2956515494734049} {:player :mark, :slot :one-sheep, :targets [], :nub 0.20908898091875017}]
  :break
  [:value [:main :game :next-move] {:type :game, :player :mark} {:type :game, :player :bryn}]
  [:value [:main :game :players :mark :moves] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []}] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []} {:slot :one-sheep, :player :mark, :targets []}]]
  [:value [:main :game :slots :one-sheep] {:action :one-sheep, :performed false, :supply 3} {:action :one-sheep, :performed :mark, :supply 0}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3}]]
  [:value [:main :game :players :mark :animals] {:sheep 0, :cattle 0, :boar 0} {:sheep 3, :cattle 0, :boar 0}]
  :break
  [:value [:main :move] {:player :mark, :slot :one-sheep, :targets [], :nub 0.20908898091875017} {:player :bryn, :slot :one-grain, :targets [], :nub 0.038918786915019155}]
  :break
  [:value [:main :game :players :bryn :moves] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []} {:slot :build-rooms, :player :bryn, :targets [{:space 2}]}] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []} {:slot :build-rooms, :player :bryn, :targets [{:space 2}]} {:slot :one-grain, :player :bryn, :targets []}]]
  [:value [:main :game :next-move] {:type :game, :player :bryn} {:type :game, :player :mark}]
  [:value [:main :game :players :bryn :resources] {:food 1, :wood 1, :clay 1, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 1, :wood 1, :clay 1, :reed 0, :stone 0, :grain 1, :vegetable 0}]
  [:value [:main :game :slots :one-grain] {:action :one-grain, :performed false} {:action :one-grain, :performed :bryn}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3}]]
  :break
  [:value [:main :move] {:player :bryn, :slot :one-grain, :targets [], :nub 0.038918786915019155} {:player :mark, :slot :one-clay, :targets [], :nub 0.9197247778065503}]
  :break
  [:value [:main :game :players :mark :resources] {:food 2, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 2, :wood 0, :clay 3, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :next-move] {:type :game, :player :mark} {:type :tick}]
  [:value [:main :game :players :mark :moves] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []} {:slot :one-sheep, :player :mark, :targets []}] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []} {:slot :one-sheep, :player :mark, :targets []} {:slot :one-clay, :player :mark, :targets []}]]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3}]]
  [:value [:main :game :slots :one-clay] {:action :one-clay, :performed false, :supply 3} {:action :one-clay, :performed :mark, :supply 0}]
  :break
  [:value [:main :tick] 3 4]
  :break
  [:value [:main :game :round] 3 4]
  [:value [:main :game :slots :one-reed] {:action :one-reed, :performed false, :supply 1} {:action :one-reed, :performed false, :supply 2}]
  [:value [:main :game :slots :fishing] {:action :fishing, :performed false, :supply 1} {:action :fishing, :performed false, :supply 2}]
  [:value [:main :game :slots :one-grain] {:action :one-grain, :performed :bryn} {:action :one-grain, :performed false}]
  [:value [:main :game :slots :one-sheep] {:action :one-sheep, :performed :mark, :supply 0} {:action :one-sheep, :performed false, :supply 1}]
  [:value [:main :game :slots :three-wood] {:action :three-wood, :performed false, :supply 3} {:action :three-wood, :performed false, :supply 6}]
  [:value [:main :game :slots :one-clay] {:action :one-clay, :performed :mark, :supply 0} {:action :one-clay, :performed false, :supply 1}]
  [:value [:main :game :slots :build-rooms] {:action :build-rooms, :performed :bryn} {:action :build-rooms, :performed false}]
  :break
  [:value [:main :move] {:player :mark, :slot :one-clay, :targets [], :nub 0.9197247778065503} {:player :bryn, :slot :fishing, :targets [], :nub 0.9503576669376343}]
  :break
  [:value [:main :game :next-move] {:type :tick} {:type :game, :player :mark}]
  [:value [:main :game :players :bryn :moves] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []} {:slot :build-rooms, :player :bryn, :targets [{:space 2}]} {:slot :one-grain, :player :bryn, :targets []}] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []} {:slot :build-rooms, :player :bryn, :targets [{:space 2}]} {:slot :one-grain, :player :bryn, :targets []} {:slot :fishing, :player :bryn, :targets []}]]
  [:value [:main :game :slots :fishing] {:action :fishing, :performed false, :supply 2} {:action :fishing, :performed :bryn, :supply 0}]
  [:value [:main :game :players :bryn :resources] {:food 1, :wood 1, :clay 1, :reed 0, :stone 0, :grain 1, :vegetable 0} {:food 3, :wood 1, :clay 1, :reed 0, :stone 0, :grain 1, :vegetable 0}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3} {:slot :fishing, :player :bryn, :targets [], :round 4}]]
  :break
  [:value [:main :move] {:player :bryn, :slot :fishing, :targets [], :nub 0.9503576669376343} {:player :mark, :slot :three-wood, :targets [], :nub 0.5165629994589835}]
  :break
  [:value [:main :game :players :mark :resources] {:food 2, :wood 0, :clay 3, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 2, :wood 6, :clay 3, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :next-move] {:type :game, :player :mark} {:type :game, :player :bryn}]
  [:value [:main :game :players :mark :moves] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []} {:slot :one-sheep, :player :mark, :targets []} {:slot :one-clay, :player :mark, :targets []}] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []} {:slot :one-sheep, :player :mark, :targets []} {:slot :one-clay, :player :mark, :targets []} {:slot :three-wood, :player :mark, :targets []}]]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3} {:slot :fishing, :player :bryn, :targets [], :round 4}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3} {:slot :fishing, :player :bryn, :targets [], :round 4} {:slot :three-wood, :player :mark, :targets [], :round 4}]]
  [:value [:main :game :slots :three-wood] {:action :three-wood, :performed false, :supply 6} {:action :three-wood, :performed :mark, :supply 0}]
  :break
  [:value [:main :move] {:player :mark, :slot :three-wood, :targets [], :nub 0.5165629994589835} {:player :bryn, :slot :day-labourer, :targets [{:resource :clay}], :nub 0.5797450172249228}]
  :break
  [:value [:main :game :players :bryn :moves] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []} {:slot :build-rooms, :player :bryn, :targets [{:space 2}]} {:slot :one-grain, :player :bryn, :targets []} {:slot :fishing, :player :bryn, :targets []}] [{:slot :three-wood, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]} {:slot :one-reed, :player :bryn, :targets []} {:slot :three-wood, :player :bryn, :targets []} {:slot :build-rooms, :player :bryn, :targets [{:space 2}]} {:slot :one-grain, :player :bryn, :targets []} {:slot :fishing, :player :bryn, :targets []} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}]}]]
  [:value [:main :game :next-move] {:type :game, :player :bryn} {:type :game, :player :mark}]
  [:value [:main :game :players :bryn :resources] {:food 3, :wood 1, :clay 1, :reed 0, :stone 0, :grain 1, :vegetable 0} {:food 4, :wood 1, :clay 2, :reed 0, :stone 0, :grain 1, :vegetable 0}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3} {:slot :fishing, :player :bryn, :targets [], :round 4} {:slot :three-wood, :player :mark, :targets [], :round 4}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3} {:slot :fishing, :player :bryn, :targets [], :round 4} {:slot :three-wood, :player :mark, :targets [], :round 4} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 4}]]
  [:value [:main :game :slots :day-labourer] {:action :day-labourer, :performed false} {:action :day-labourer, :performed :bryn}]
  :break
  [:value [:main :move] {:player :bryn, :slot :day-labourer, :targets [{:resource :clay}], :nub 0.5797450172249228} {:player :mark, :slot :fences, :targets [{:side :n, :space 3} {:side :e, :space 3} {:side :s, :space 3} {:side :w, :space 3}], :nub 0.9986743361223489}]
  :break
  [:value [:main :game :players :mark :board 3] {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :resource {:type nil, :number nil}} {:hut nil, :fences {:n true, :e true, :s true, :w true}, :stable nil, :field nil, :resource {:type nil, :number nil}}]
  [:value [:main :game :players :mark :resources] {:food 2, :wood 6, :clay 3, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 2, :wood 2, :clay 3, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:value [:main :game :next-move] {:type :game, :player :mark} {:type :harvest, :player :bryn}]
  [:value [:main :game :players :mark :moves] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []} {:slot :one-sheep, :player :mark, :targets []} {:slot :one-clay, :player :mark, :targets []} {:slot :three-wood, :player :mark, :targets []}] [{:slot :plow, :player :mark, :targets [{:space 2}]} {:slot :one-grain, :player :mark, :targets []} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}]} {:slot :fishing, :player :mark, :targets []} {:slot :one-sheep, :player :mark, :targets []} {:slot :one-clay, :player :mark, :targets []} {:slot :three-wood, :player :mark, :targets []} {:slot :fences, :player :mark, :targets [{:side :n, :space 3} {:side :e, :space 3} {:side :s, :space 3} {:side :w, :space 3}]}]]
  [:value [:main :game :slots :fences] {:action :fences, :performed false} {:action :fences, :performed :mark}]
  [:value [:main :game :moves] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3} {:slot :fishing, :player :bryn, :targets [], :round 4} {:slot :three-wood, :player :mark, :targets [], :round 4} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 4}] [{:slot :three-wood, :player :bryn, :targets [], :round 1} {:slot :plow, :player :mark, :targets [{:space 2}], :round 1} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 1} {:slot :one-grain, :player :mark, :targets [], :round 1} {:slot :one-reed, :player :bryn, :targets [], :round 2} {:slot :sow, :player :mark, :targets [{:resource :grain, :space 2}], :round 2} {:slot :three-wood, :player :bryn, :targets [], :round 2} {:slot :fishing, :player :mark, :targets [], :round 2} {:slot :build-rooms, :player :bryn, :targets [{:space 2}], :round 3} {:slot :one-sheep, :player :mark, :targets [], :round 3} {:slot :one-grain, :player :bryn, :targets [], :round 3} {:slot :one-clay, :player :mark, :targets [], :round 3} {:slot :fishing, :player :bryn, :targets [], :round 4} {:slot :three-wood, :player :mark, :targets [], :round 4} {:slot :day-labourer, :player :bryn, :targets [{:resource :clay}], :round 4} {:slot :fences, :player :mark, :targets [{:side :n, :space 3} {:side :e, :space 3} {:side :s, :space 3} {:side :w, :space 3}], :round 4}]]
 ]}