{:config {:order 0, :description ":main", :name :main}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :resources] :map]
  [:transform-enable [:main :resources] :swap [{:io.pedestal.app.messages/topic [:game :players :bryn :resources], :value {:food 100, :wood 100, :clay 100, :reed 100, :stone 100, :grain 100, :vegetable 100}}]]
  [:node-create [:main :tick] :map]
  [:transform-enable [:main :tick] :do-tick [{:io.pedestal.app.messages/type :inc, :io.pedestal.app.messages/topic [:tick]}]]
  [:node-create [:main :move] :map]
  [:transform-enable [:main :move] :perform-move [{:io.pedestal.app.messages/topic [:move], :io.pedestal.app.messages.param/player {:read-as :data}, :io.pedestal.app.messages.param/slot {:read-as :data}, :io.pedestal.app.messages.param/targets {:read-as :data}}]]
  [:node-create [:main :game] :map]
  [:node-create [:main :game :game-id] :map]
  [:value [:main :game :game-id] nil 1]
  [:node-create [:main :game :players] :map]
  [:node-create [:main :game :players :bryn] :map]
  [:node-create [:main :game :players :bryn :starting-player] :map]
  [:value [:main :game :players :bryn :starting-player] nil true]
  [:node-create [:main :game :players :bryn :board] :map]
  [:node-create [:main :game :players :bryn :board 0] :map]
  [:value [:main :game :players :bryn :board 0] nil {:hut :wood, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 1] :map]
  [:value [:main :game :players :bryn :board 1] nil {:hut :wood, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 2] :map]
  [:value [:main :game :players :bryn :board 2] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 3] :map]
  [:value [:main :game :players :bryn :board 3] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 4] :map]
  [:value [:main :game :players :bryn :board 4] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 5] :map]
  [:value [:main :game :players :bryn :board 5] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 6] :map]
  [:value [:main :game :players :bryn :board 6] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 7] :map]
  [:value [:main :game :players :bryn :board 7] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 8] :map]
  [:value [:main :game :players :bryn :board 8] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 9] :map]
  [:value [:main :game :players :bryn :board 9] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 10] :map]
  [:value [:main :game :players :bryn :board 10] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 11] :map]
  [:value [:main :game :players :bryn :board 11] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 12] :map]
  [:value [:main :game :players :bryn :board 12] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 13] :map]
  [:value [:main :game :players :bryn :board 13] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :board 14] :map]
  [:value [:main :game :players :bryn :board 14] nil {:hut nil, :fences {:n nil, :e nil, :s nil, :w nil}, :stable nil, :field nil, :animal {:type nil, :number nil}}]
  [:node-create [:main :game :players :bryn :moves] :map]
  [:value [:main :game :players :bryn :moves] nil []]
  [:node-create [:main :game :players :bryn :resources] :map]
  [:value [:main :game :players :bryn :resources] nil {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0}]
  [:node-create [:main :game :players :bryn :name] :map]
  [:value [:main :game :players :bryn :name] nil "Bryn"]
  [:node-create [:main :game :players :bryn :animals] :map]
  [:value [:main :game :players :bryn :animals] nil {:sheep 0, :cattle 0, :boar 0}]
  [:node-create [:main :game :players :bryn :family] :map]
  [:value [:main :game :players :bryn :family] nil 2]
  [:node-create [:main :game :slots] :map]
  [:node-create [:main :game :slots :starting-player] :map]
  [:value [:main :game :slots :starting-player] nil {:action :starting-player, :performed false}]
  [:node-create [:main :game :slots :build-stable] :map]
  [:value [:main :game :slots :build-stable] nil {:action :build-stable, :performed false}]
  [:node-create [:main :game :slots :one-grain] :map]
  [:value [:main :game :slots :one-grain] nil {:action :one-grain, :performed false}]
  [:node-create [:main :game :slots :three-wood] :map]
  [:value [:main :game :slots :three-wood] nil {:action :three-wood, :performed false, :supply 3}]
  [:node-create [:main :game :slots :build-rooms] :map]
  [:value [:main :game :slots :build-rooms] nil {:action :build-rooms, :performed false}]
  [:node-create [:main :game :slots :plow] :map]
  [:value [:main :game :slots :plow] nil {:action :plow, :performed false}]
  :break
  [:value [:main :tick] nil 2]
  :break
  [:value [:main :game :slots :three-wood] {:action :three-wood, :performed false, :supply 3} {:action :three-wood, :performed false, :supply 6}]
  :break
  [:value [:main :tick] 2 3]
  :break
  [:value [:main :game :slots :three-wood] {:action :three-wood, :performed false, :supply 6} {:action :three-wood, :performed false, :supply 9}]
  :break
  [:value [:main :move] nil {:player :bryn, :slot :one-grain, :targets [], :nub 0.0762402571272105}]
  :break
  [:value [:main :game :players :bryn :moves] [] [{:slot :one-grain, :player :bryn, :targets []}]]
  [:value [:main :game :players :bryn :resources] {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 0, :vegetable 0} {:food 0, :wood 0, :clay 0, :reed 0, :stone 0, :grain 1, :vegetable 0}]
  [:value [:main :game :slots :one-grain] {:action :one-grain, :performed false} {:action :one-grain, :performed :bryn}]
 ]}